namespace ChessDotNet.Public
{
    public class PublicData
    {
        public const string DefaultChessPosition = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";

        public static readonly ChessSquare[] Squares = {
            new ChessSquare("a8"),
            new ChessSquare("b8"),
            new ChessSquare("c8"),
            new ChessSquare("d8"),
            new ChessSquare("e8"),
            new ChessSquare("f8"),
            new ChessSquare("g8"),
            new ChessSquare("h8"),
            new ChessSquare("a7"),
            new ChessSquare("b7"),
            new ChessSquare("c7"),
            new ChessSquare("d7"),
            new ChessSquare("e7"),
            new ChessSquare("f7"),
            new ChessSquare("g7"),
            new ChessSquare("h7"),
            new ChessSquare("a6"),
            new ChessSquare("b6"),
            new ChessSquare("c6"),
            new ChessSquare("d6"),
            new ChessSquare("e6"),
            new ChessSquare("f6"),
            new ChessSquare("g6"),
            new ChessSquare("h6"),
            new ChessSquare("a5"),
            new ChessSquare("b5"),
            new ChessSquare("c5"),
            new ChessSquare("d5"),
            new ChessSquare("e5"),
            new ChessSquare("f5"),
            new ChessSquare("g5"),
            new ChessSquare("h5"),
            new ChessSquare("a4"),
            new ChessSquare("b4"),
            new ChessSquare("c4"),
            new ChessSquare("d4"),
            new ChessSquare("e4"),
            new ChessSquare("f4"),
            new ChessSquare("g4"),
            new ChessSquare("h4"),
            new ChessSquare("a3"),
            new ChessSquare("b3"),
            new ChessSquare("c3"),
            new ChessSquare("d3"),
            new ChessSquare("e3"),
            new ChessSquare("f3"),
            new ChessSquare("g3"),
            new ChessSquare("h3"),
            new ChessSquare("a2"),
            new ChessSquare("b2"),
            new ChessSquare("c2"),
            new ChessSquare("d2"),
            new ChessSquare("e2"),
            new ChessSquare("f2"),
            new ChessSquare("g2"),
            new ChessSquare("h2"),
            new ChessSquare("a1"),
            new ChessSquare("b1"),
            new ChessSquare("c1"),
            new ChessSquare("d1"),
            new ChessSquare("e1"),
            new ChessSquare("f1"),
            new ChessSquare("g1"),
            new ChessSquare("h1"),
        };
    }
}
